import type { JobResult, PipelineStage } from '../types/api'

const pipelineStage = (
  name: string,
  duration_ms: number,
  confidence_score?: number,
  summary?: Record<string, unknown>,
): PipelineStage => ({
  name,
  status: 'success',
  duration_ms,
  confidence_score,
  summary,
})

export const mockJobResult: JobResult = {
  dataset_id: 'demo_customer_2026',
  total_rows: 136,
  issues_detected: 24,
  fixes_applied: 18,
  overall_confidence: 0.89,
  validation_passed: true,
  duration_seconds: 6.4,
  fix_breakdown: {
    numeric_outlier: 3,
    format_violation: 8,
    missing: 5,
    rare_category: 2,
  },
  iterations: 1,
  output_path: '/api/download/demo',
  pipeline_stages: {
    ingest: pipelineStage('ingest', 45, undefined, { rows: 136, columns: 8 }),
    reconstruction_schema_planner: pipelineStage('reconstruction_schema_planner', 3021, 0.94, {
      schema_found: true,
      delimiter: '|',
    }),
    structure_reconstruction: pipelineStage('structure_reconstruction', 140, 0.91, {
      rows_parsed: 84,
      rows_dropped: 8,
      duplicates_removed: 9,
    }),
    schema_analysis: pipelineStage('schema_analysis', 20, undefined, { columns_inferred: 8 }),
    data_profiling: pipelineStage('data_profiling', 32, 0.94, { profile_columns: 8 }),
    anomaly_detection: pipelineStage('anomaly_detection', 24, undefined, { anomaly_count: 15 }),
    cleaning: pipelineStage('cleaning', 2050, 0.81, { fix_count: 18 }),
    validation: pipelineStage('validation', 15, 0.89, { validation_passed: true }),
    confidence_scoring: pipelineStage('confidence_scoring', 10, 0.89, { low_confidence_count: 3 }),
  },
  stage_previews: {},
  raw_preview: {
    rows: [
      {
        blob: '101 | John | Smith | 22 | M | Data Science | 2022-05-15 | $1200',
      },
      {
        blob: '102 | Jane | Davis | 29 | F | Analytics | 2021-01-01 | $1800',
      },
    ],
    row_count: 2,
    column_names: ['blob'],
    truncated: false,
  },
  cleaned_preview: {
    rows: [
      {
        Student_ID: '101',
        First_Name: 'John',
        Last_Name: 'Smith',
        Age: '22',
        Gender: 'M',
        Course: 'Data Science',
        Enrollment_Date: '2022-05-15',
        Total_Payments: '1200',
      },
      {
        Student_ID: '102',
        First_Name: 'Jane',
        Last_Name: 'Davis',
        Age: '29',
        Gender: 'F',
        Course: 'Analytics',
        Enrollment_Date: '2021-01-01',
        Total_Payments: '1800',
      },
    ],
    row_count: 2,
    column_names: [
      'Student_ID',
      'First_Name',
      'Last_Name',
      'Age',
      'Gender',
      'Course',
      'Enrollment_Date',
      'Total_Payments',
    ],
    truncated: false,
  },
  reconstruction_report: {
    rows_parsed: 84,
    rows_dropped: 8,
    duplicates_removed: 9,
    output_rows: 75,
  },
  inferred_schema: {
    Student_ID: { dtype: 'integer' },
    Enrollment_Date: { dtype: 'date', format_pattern: 'date_iso' },
    Total_Payments: { dtype: 'integer' },
  },
  schema_issues: [],
  profile_report: {
    Student_ID: { column: 'Student_ID', null_pct: 0, unique_pct: 100, is_numeric: true, mean: 104 },
    Total_Payments: { column: 'Total_Payments', null_pct: 3, unique_pct: 65, is_numeric: true, mean: 1420 },
    Course: {
      column: 'Course',
      null_pct: 1,
      unique_pct: 12,
      is_numeric: false,
      top_values: { 'Data Science': 28, Analytics: 18, 'Machine Learning': 16 },
    },
  },
  anomalies: [
    {
      row: 4,
      column: 'Total_Payments',
      value: '$0',
      anomaly_type: 'numeric_outlier',
      severity: 'warning',
      details: 'Outside expected range',
    },
  ],
  audit_log: [],
  cleaning_actions: [
    {
      row: 4,
      column: 'Total_Payments',
      old_value: '$0',
      new_value: '900',
      rule: 'llm:gpt-4o',
      confidence: 0.68,
      reasoning: 'Context suggests missing leading digit.',
      issue_type: 'numeric_outlier',
    },
  ],
  llm_logs: [
    {
      row: 4,
      column: 'Total_Payments',
      model: 'gpt-4o',
      prompt: 'Column: Total_Payments',
      structured_output: { corrected_value: '900', confidence: 0.68 },
      confidence: 0.68,
      reasoning: 'Context suggests missing leading digit.',
    },
  ],
  review_queue: [
    {
      id: 'review-0',
      status: 'pending',
      row: 4,
      column: 'Total_Payments',
      old_value: '$0',
      suggested_value: '900',
      confidence: 0.68,
      reasoning: 'Context suggests missing leading digit.',
      issue_type: 'numeric_outlier',
      fix_method: 'llm:gpt-4o',
    },
  ],
  low_confidence_fixes: [],
  cleaned_records: [],
  chunk_results: [],
}
